services:
  backend-1:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_NAME: Server_1
    ports:
      - "5101:8080"

  backend-2:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_NAME: Server_2
    ports:
      - "5102:8080"

  backend-3:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_NAME: Server_3
    ports:
      - "5103:8080"

  backend-4:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_NAME: Server_4
    ports:
      - "5104:8080"

  backend-5:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_NAME: Server_5
    ports:
      - "5105:8080"

  backend-6:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_NAME: Server_6
    ports:
      - "5106:8080"

  load-balancer:
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    depends_on:
      - backend-1
      - backend-2
      - backend-3
      - backend-4
      - backend-5
      - backend-6
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Settings__Backends__0__Name: Server_1
      Settings__Backends__0__Host: backend-1
      Settings__Backends__0__Port: 8080
      Settings__Backends__0__Weight: 1
      Settings__Backends__1__Name: Server_2
      Settings__Backends__1__Host: backend-2
      Settings__Backends__1__Port: 8080
      Settings__Backends__1__Weight: 1
      Settings__Backends__2__Name: Server_3
      Settings__Backends__2__Host: backend-3
      Settings__Backends__2__Port: 8080
      Settings__Backends__2__Weight: 1
      Settings__Backends__3__Name: Server_4
      Settings__Backends__3__Host: backend-4
      Settings__Backends__3__Port: 8080
      Settings__Backends__3__Weight: 1
      Settings__Backends__4__Name: Server_5
      Settings__Backends__4__Host: backend-5
      Settings__Backends__4__Port: 8080
      Settings__Backends__4__Weight: 1
      Settings__Backends__5__Name: Server_6
      Settings__Backends__5__Host: backend-6
      Settings__Backends__5__Port: 8080
      Settings__Backends__5__Weight: 1
    ports:
      - "5120:8080"

  frontend:
    build:
      context: .
      dockerfile: Frontendondon/Dockerfile
    depends_on:
      - load-balancer
    ports:
      - "5173:80"
